## Import Libraries

In [ ]:
import os
import pandas as pd
import geopandas as gpd

from zipfile import ZipFile

from pathlib import Path
from sqlalchemy import create_engine, text
from geoalchemy2 import Geometry

## Connection String

In [2]:
DB_USER = "postgres"
DB_PASSWORD = "password"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "citibike"

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)


DATABASE_URL

'postgresql+psycopg2://postgres:password@localhost:5432/citibike'

## Parameters with Masking

In [3]:
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = os.getenv("DB_NAME")

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

In [4]:
engine = create_engine(DATABASE_URL)

engine

Engine(postgresql+psycopg2://postgres:***@localhost:5432/citibike)

## Testing the Connections

In [5]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT version();"))
    print(result.fetchone()[0])

PostgreSQL 17.0 (Debian 17.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

In [6]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT PostGIS_Version();"))
    print(result.fetchone()[0])

3.4 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

## Loading the CitiBike Data

### Defining File Paths

In [7]:
DATA_DIR = Path("../data/JC")

citibike_path = DATA_DIR / "JC2025.csv"
weather_path = DATA_DIR / "jersey_weather_2025.csv"
neighborhood_path = DATA_DIR / "jersey-city-neighborhoods.geojson"

### Reading the data

In [8]:
citibike_df = pd.read_csv(citibike_path)

citibike_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,9F734BE1BFC45FF4,electric_bike,2025-11-18 18:34:14.943,2025-11-18 18:47:33.391,Glenwood Ave,JC094,West Side Ave & Stegman Pkwy,JC131,40.727551,-74.071061,40.710870,-74.093680,member
1,B6C773B13AC0E465,classic_bike,2025-11-26 16:29:15.513,2025-11-26 16:43:45.235,Glenwood Ave,JC094,West Side Ave & Stegman Pkwy,JC131,40.727551,-74.071061,40.710870,-74.093680,member
2,C300465AA158280F,electric_bike,2025-11-04 22:31:58.010,2025-11-04 22:38:57.017,Bloomfield St & 15 St,HB203,Marshall St & 2 St,HB408,40.754530,-74.026580,40.740802,-74.042521,member
3,31A424FC97C8AAFB,classic_bike,2025-11-08 06:51:57.424,2025-11-08 06:57:45.627,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member
4,08C5EA04CB1FDC57,classic_bike,2025-11-24 20:31:21.758,2025-11-24 20:38:01.261,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member

In [9]:
citibike_df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str')

### Cleaning the data

In [10]:
citibike_df["started_at"] = pd.to_datetime(
    citibike_df["started_at"],
    errors="coerce"
)

citibike_df["ended_at"] = pd.to_datetime(
    citibike_df["ended_at"],
    errors="coerce"
)

### Create a date column for easier joins with weather data.

In [11]:
citibike_df["ride_date"] = citibike_df["started_at"].dt.date

citibike_df["ride_date"] = pd.to_datetime(
    citibike_df["ride_date"],
    errors="coerce"
)

citibike_df[
    [
        "ride_id",
        "started_at",
        "ended_at",
        "ride_date"
    ]
].head()

            ride_id              started_at                ended_at  ride_date
0  9F734BE1BFC45FF4 2025-11-18 18:34:14.943 2025-11-18 18:47:33.391 2025-11-18
1  B6C773B13AC0E465 2025-11-26 16:29:15.513 2025-11-26 16:43:45.235 2025-11-26
2  C300465AA158280F 2025-11-04 22:31:58.010 2025-11-04 22:38:57.017 2025-11-04
3  31A424FC97C8AAFB 2025-11-08 06:51:57.424 2025-11-08 06:57:45.627 2025-11-08
4  08C5EA04CB1FDC57 2025-11-24 20:31:21.758 2025-11-24 20:38:01.261 2025-11-24

### Writing CitiBike data to PostgreSQL Database

In [12]:
citibike_df.to_sql(
    name="jersey_city",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=50_000,
    method="multi"
)

1002704

### Checking the resutls

In [13]:
DATABASE_URL

'postgresql+psycopg2://postgres:password@localhost:5432/citibike'

In [14]:
query = """
SELECT
    
    *

FROM jersey_city
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_date
0,9F734BE1BFC45FF4,electric_bike,2025-11-18 18:34:14.943,2025-11-18 18:47:33.391,Glenwood Ave,JC094,West Side Ave & Stegman Pkwy,JC131,40.727551,-74.071061,40.710870,-74.093680,member,2025-11-18
1,B6C773B13AC0E465,classic_bike,2025-11-26 16:29:15.513,2025-11-26 16:43:45.235,Glenwood Ave,JC094,West Side Ave & Stegman Pkwy,JC131,40.727551,-74.071061,40.710870,-74.093680,member,2025-11-26
2,C300465AA158280F,electric_bike,2025-11-04 22:31:58.010,2025-11-04 22:38:57.017,Bloomfield St & 15 St,HB203,Marshall St & 2 St,HB408,40.754530,-74.026580,40.740802,-74.042521,member,2025-11-04
3,31A424FC97C8AAFB,classic_bike,2025-11-08 06:51:57.424,2025-11-08 06:57:45.627,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member,2025-11-08
4,08C5EA04CB1FDC57,classic_bike,2025-11-24 20:31:21.758,2025-11-24 20:38:01.261,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member,2025-11-24

In [15]:
weather_df = pd.read_csv(weather_path)

weather_df.head()

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,11.0,3.9,7.4,4.5,4.5,0.0,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.0,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.0,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1,2025-01-04
4,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9,2025-01-05

In [16]:
weather_df.dtypes

temperature_2m_max     float64
temperature_2m_min     float64
temperature_2m_mean    float64
precipitation_sum      float64
rain_sum               float64
snowfall_sum           float64
wind_speed_10m_max     float64
date                       str
dtype: object

In [17]:
weather_df["date"] = pd.to_datetime(
    weather_df["date"],
    errors="coerce"
)

weather_df.head()

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,11.0,3.9,7.4,4.5,4.5,0.0,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.0,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.0,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1,2025-01-04
4,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9,2025-01-05

In [18]:
weather_df.dtypes

temperature_2m_max            float64
temperature_2m_min            float64
temperature_2m_mean           float64
precipitation_sum             float64
rain_sum                      float64
snowfall_sum                  float64
wind_speed_10m_max            float64
date                   datetime64[us]
dtype: object

In [19]:
#| echo: true

weather_df.to_sql(
    name="jersey_weather",
    con=engine,
    if_exists="replace",
    index=False
)

365

In [20]:
query = """
SELECT
    *
FROM jersey_weather
LIMIT 10;
"""

pd.read_sql(
    query,
    con=engine
)

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,11.0,3.9,7.4,4.5,4.5,0.00,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.00,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.00,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.00,26.1,2025-01-04
4,0.4,-3.6,-2.2,0.0,0.0,0.00,19.9,2025-01-05
5,-1.6,-4.5,-2.3,1.7,0.0,1.19,16.7,2025-01-06
6,-3.0,-8.7,-5.2,0.0,0.0,0.00,29.9,2025-01-07
7,-2.5,-6.6,-4.3,0.0,0.0,0.00,25.4,2025-01-08
8,-1.5,-6.8,-4.2,0.0,0.0,0.00,29.0,2025-01-09
9,3.3,-3.9,-0.9,0.0,0.0,0.00,22.5,2025-01-10

### Read GeoJSON with GeoPandas

In [21]:
neighborhood_gdf = gpd.read_file(neighborhood_path)

neighborhood_gdf.head()

,cartodb_id,area_sq_ft,acres,area,neighborhood,color,lon,lat,geometry
0,38,411601381.8,9449.068,Greenville,Port Liberte,NaN,-74.074540,40.694202,"POLYGON ((-74.06862 40.70098, -74.06808 40.696..."
1,52,411601381.8,9449.068,Bergen-Lafayette,LSP Industrial,NaN,-74.062358,40.699189,"POLYGON ((-74.06808 40.69684, -74.06862 40.700..."
2,29,411601381.8,9449.068,West Side,Hackensack,NaN,-74.085147,40.735520,"POLYGON ((-74.07601 40.73822, -74.07781 40.737..."
3,35,411601381.8,9449.068,Bergen-Lafayette,Lafayette,12.0,-74.061279,40.712676,"POLYGON ((-74.056 40.71735, -74.056 40.71692, ..."
4,51,411601381.8,9449.068,Greenville,Jackson Hill,15.0,-74.085503,40.700791,"POLYGON ((-74.07561 40.70233, -74.0758 40.7020..."

In [22]:
neighborhood_gdf.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [23]:
neighborhood_gdf.geom_type.value_counts()

Polygon    53
Name: count, dtype: int64

In [24]:
#| echo: true

neighborhood_gdf.to_postgis(
    name="jersey_city_neighborhoods",
    con=engine,
    if_exists="replace",
    index=False
)

In [25]:


query = """
SELECT
    neighborhood,
    ST_GeometryType(geometry) AS geometry_type,
    ST_SRID(geometry) AS srid
FROM jersey_city_neighborhoods
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

     neighborhood geometry_type  srid
0    Port Liberte    ST_Polygon  4326
1  LSP Industrial    ST_Polygon  4326
2      Hackensack    ST_Polygon  4326
3       Lafayette    ST_Polygon  4326
4    Jackson Hill    ST_Polygon  4326

## Create Station Spatial Table

### Create Station Summary

In [26]:
start_stations = citibike_df[
    [
        "ride_id",
        "start_station_id",
        "start_station_name",
        "start_lat",
        "start_lng"
    ]
].copy()

start_stations = start_stations.rename(
    columns={
        "start_station_id": "station_id",
        "start_station_name": "station_name",
        "start_lat": "lat",
        "start_lng": "lng"
    }
)

start_stations["activity_type"] = "departure"

In [27]:
end_stations = citibike_df[
    [
        "ride_id",
        "end_station_id",
        "end_station_name",
        "end_lat",
        "end_lng"
    ]
].copy()

end_stations = end_stations.rename(
    columns={
        "end_station_id": "station_id",
        "end_station_name": "station_name",
        "end_lat": "lat",
        "end_lng": "lng"
    }
)

end_stations["activity_type"] = "arrival"

In [28]:
station_activity_long = pd.concat(
    [
        start_stations,
        end_stations
    ],
    ignore_index=True
)

station_activity_long = station_activity_long.dropna(
    subset=[
        "station_id",
        "station_name",
        "lat",
        "lng"
    ]
)

In [29]:
station_activity_agg = (
    station_activity_long
    .groupby(
        [
            "station_id",
            "station_name",
            "lat",
            "lng",
            "activity_type"
        ],
        as_index=False
    )
    .agg(
        number_of_rides=("ride_id", "count")
    )
)

In [30]:
station_summary = (
    station_activity_agg
    .pivot_table(
        index=[
            "station_id",
            "station_name",
            "lat",
            "lng"
        ],
        columns="activity_type",
        values="number_of_rides",
        fill_value=0
    )
    .reset_index()
)

station_summary.columns.name = None

station_summary = station_summary.rename(
    columns={
        "departure": "total_departures",
        "arrival": "total_arrivals"
    }
)

if "total_departures" not in station_summary.columns:
    station_summary["total_departures"] = 0

if "total_arrivals" not in station_summary.columns:
    station_summary["total_arrivals"] = 0

station_summary["total_activity"] = (
    station_summary["total_departures"] +
    station_summary["total_arrivals"]
)

station_summary["net_departures"] = (
    station_summary["total_departures"] -
    station_summary["total_arrivals"]
)

station_summary = station_summary.sort_values(
    "total_activity",
    ascending=False
).reset_index(drop=True)

station_summary.head()

,station_id,station_name,lat,lng,total_arrivals,total_departures,total_activity,net_departures
0,JC115,Grove St PATH,40.719410,-74.043090,47744.0,45121.0,92865.0,-2623.0
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,26638.0,25964.0,52602.0,-674.0
2,JC009,Hamilton Park,40.727596,-74.044247,22347.0,22311.0,44658.0,-36.0
3,HB106,River St & Newark St,40.736722,-74.029007,22113.0,21489.0,43602.0,-624.0
4,JC066,Newport PATH,40.727224,-74.033759,20698.0,20704.0,41402.0,6.0

### Convert Station Summary to GeoDataFrame

In [31]:
station_gdf = gpd.GeoDataFrame(
    station_summary,
    geometry=gpd.points_from_xy(
        station_summary["lng"],
        station_summary["lat"]
    ),
    crs="EPSG:4326"
)

station_gdf.head()

,station_id,station_name,lat,lng,total_arrivals,total_departures,total_activity,net_departures,geometry
0,JC115,Grove St PATH,40.719410,-74.043090,47744.0,45121.0,92865.0,-2623.0,POINT (-74.04309 40.71941)
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,26638.0,25964.0,52602.0,-674.0,POINT (-74.0303 40.73594)
2,JC009,Hamilton Park,40.727596,-74.044247,22347.0,22311.0,44658.0,-36.0,POINT (-74.04425 40.7276)
3,HB106,River St & Newark St,40.736722,-74.029007,22113.0,21489.0,43602.0,-624.0,POINT (-74.02901 40.73672)
4,JC066,Newport PATH,40.727224,-74.033759,20698.0,20704.0,41402.0,6.0,POINT (-74.03376 40.72722)

### Write Station Points to PostGIS

In [32]:
station_gdf.to_postgis(
    name="jc_2025_stations",
    con=engine,
    if_exists="replace",
    index=False
)

In [33]:


query = """
SELECT
    station_id,
    station_name,
    total_activity,
    ST_GeometryType(geometry) AS geometry_type,
    ST_SRID(geometry) AS srid
FROM jc_2025_stations
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

,station_id,station_name,total_activity,geometry_type,srid
0,JC115,Grove St PATH,92865.0,ST_Point,4326
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,52602.0,ST_Point,4326
2,JC009,Hamilton Park,44658.0,ST_Point,4326
3,HB106,River St & Newark St,43602.0,ST_Point,4326
4,JC066,Newport PATH,41402.0,ST_Point,4326

# SQLAlchemy

### List Tables

In [34]:

query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
"""

pd.read_sql(
    query,
    con=engine
)

                  table_name
0          geography_columns
1           geometry_columns
2           jc_2025_stations
3                jersey_city
4  jersey_city_neighborhoods
5             jersey_weather
6            spatial_ref_sys

In [36]:
pd.read_sql("""
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
""", con=engine)

                  table_name
0          geography_columns
1           geometry_columns
2           jc_2025_stations
3                jersey_city
4  jersey_city_neighborhoods
5             jersey_weather
6            spatial_ref_sys

### Count Rows for each table

In [49]:

query = """
    SELECT 'jersey_city' AS table_name, COUNT(*) AS row_count FROM jersey_city
    UNION ALL
    SELECT 'jersey_weather' AS table_name, COUNT(*) AS row_count FROM jersey_weather
    UNION ALL
    SELECT 'jersey_city_neighborhoods' AS table_name, COUNT(*) AS row_count FROM jersey_city_neighborhoods
    UNION ALL
    SELECT 'jc_2025_stations' AS table_name, COUNT(*) AS row_count FROM jc_2025_stations;
"""

pd.read_sql(
    query,
    con=engine
)

                  table_name  row_count
0                jersey_city    1002704
1             jersey_weather        365
2  jersey_city_neighborhoods         53
3           jc_2025_stations        488

### Daily Ride Volume

In [50]:
query = """
    SELECT
        started_at::date AS ride_date,
        COUNT(*) AS number_of_rides
    FROM jersey_city
    GROUP BY started_at::date
    ORDER BY ride_date;
"""

daily_rides_sql = pd.read_sql(
    query,
    con=engine
)

daily_rides_sql.head()

    ride_date  number_of_rides
0  2024-12-31                2
1  2025-01-01             1179
2  2025-01-02             1711
3  2025-01-03             1771
4  2025-01-04             1337

### Join Citi Bike and Weather

In [51]:
query = """
SELECT
    c.started_at::date AS ride_date,
    COUNT(*) AS number_of_rides,
    w.temperature_2m_mean,
    w.precipitation_sum,
    w.rain_sum,
    w.snowfall_sum,
    w.wind_speed_10m_max
FROM jersey_city AS c
LEFT JOIN jersey_weather AS w
    ON c.started_at::date = w.date::date
GROUP BY
    c.started_at::date,
    w.temperature_2m_mean,
    w.precipitation_sum,
    w.rain_sum,
    w.snowfall_sum,
    w.wind_speed_10m_max
ORDER BY ride_date;
"""

bike_weather_sql = pd.read_sql(
    query,
    con=engine
)

bike_weather_sql.head()

,ride_date,number_of_rides,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max
0,2024-12-31,2,NaN,NaN,NaN,NaN,NaN
1,2025-01-01,1179,7.4,4.5,4.5,0.0,23.2
2,2025-01-02,1711,2.6,0.0,0.0,0.0,25.1
3,2025-01-03,1771,0.4,0.0,0.0,0.0,17.1
4,2025-01-04,1337,-1.4,0.0,0.0,0.0,26.1

### Spatial Join in SQL: Stations to Neighborhoods

In [53]:
#| echo: true

query = """
SELECT
    s.station_id,
    s.station_name,
    s.total_departures,
    s.total_arrivals,
    s.total_activity,
    s.net_departures,
    n.neighborhood
FROM jc_2025_stations AS s
JOIN jersey_city_neighborhoods AS n
    ON ST_Within(s.geometry, n.geometry)
ORDER BY s.total_activity DESC;
"""

station_neighborhood_sql = pd.read_sql(
    query,
    con=engine
)

station_neighborhood_sql.head()

,station_id,station_name,total_departures,total_arrivals,total_activity,net_departures,neighborhood
0,JC115,Grove St PATH,45121.0,47744.0,92865.0,-2623.0,Van Vorst Park
1,JC009,Hamilton Park,22311.0,22347.0,44658.0,-36.0,Hamilton Park
2,JC066,Newport PATH,20704.0,20698.0,41402.0,6.0,Newport
3,JC109,Bergen Ave & Sip Ave,20469.0,20357.0,40826.0,112.0,Journal Square
4,JC116,Exchange Pl,20066.0,20144.0,40210.0,-78.0,Exchange Place

### Aggregate Station Activity by Neighborhood in SQL

In [55]:

query = """
SELECT
    n.neighborhood,
    COUNT(DISTINCT s.station_id) AS number_of_stations,
    SUM(s.total_departures) AS total_departures,
    SUM(s.total_arrivals) AS total_arrivals,
    SUM(s.total_activity) AS total_activity,
    SUM(s.net_departures) AS net_departures,
    SUM(s.total_activity)::numeric / NULLIF(COUNT(DISTINCT s.station_id), 0) AS avg_activity_per_station
FROM jersey_city_neighborhoods AS n
LEFT JOIN jc_2025_stations AS s
    ON ST_Within(s.geometry, n.geometry)
GROUP BY n.neighborhood
ORDER BY total_activity DESC;
"""

neighborhood_activity_sql = pd.read_sql(
    query,
    con=engine
)

neighborhood_activity_sql.head()

,neighborhood,number_of_stations,total_departures,total_arrivals,total_activity,net_departures,avg_activity_per_station
0,Liberty State Park,0,NaN,NaN,NaN,NaN,NaN
1,Western Slope,0,NaN,NaN,NaN,NaN,NaN
2,LSP Industrial,0,NaN,NaN,NaN,NaN,NaN
3,Canal Crossing,0,NaN,NaN,NaN,NaN,NaN
4,Country Village,0,NaN,NaN,NaN,NaN,NaN

### Create Spatial Indexes

In [57]:
with engine.begin() as connection:
    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_jc_stations_geom
        ON jc_2025_stations
        USING GIST (geometry);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_jersey_city_neighborhoods_geom
        ON jersey_city_neighborhoods
        USING GIST (geometry);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_jc_started_at
        ON jersey_city (started_at);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_weather_date
        ON jersey_weather (date);
    """))

## SQLAlchemy Core

In [59]:
with engine.connect() as connection:
    connection.execute(text("CREATE TABLE IF NOT EXISTS people (name TEXT, age INTEGER)"))
    connection.execute(text("INSERT INTO people (name, age) VALUES ('Mike', 30)"))
    connection.commit() # Important: Changes must be committed to persist [7, 8]

### Defining Tables MetaData

In [58]:
from sqlalchemy import MetaData, Table, Column, Integer, String

meta = MetaData()

people = Table(
    "people", meta,
    Column("id", Integer, primary_key=True),
    Column("name", String, nullable=False),
    Column("age", Integer)
)

In [60]:
meta.create_all(engine)

## Tableau with SQLAlchemy

### Create Materialized View with SQLAlchemy

In [63]:
create_tableau_materialized_view_sql = """
DROP MATERIALIZED VIEW IF EXISTS mv_tableau_citibike_dashboard;

CREATE MATERIALIZED VIEW mv_tableau_citibike_dashboard AS
WITH ride_base AS (
    SELECT
        c.ride_id,
        c.rideable_type,
        c.member_casual,

        c.started_at,
        c.ended_at,
        c.started_at::date AS ride_date,

        EXTRACT(YEAR FROM c.started_at)::int AS ride_year,
        EXTRACT(QUARTER FROM c.started_at)::int AS ride_quarter,
        EXTRACT(MONTH FROM c.started_at)::int AS ride_month,
        TO_CHAR(c.started_at, 'Month') AS ride_month_name,
        TO_CHAR(c.started_at, 'Day') AS ride_day_of_week,
        EXTRACT(ISODOW FROM c.started_at)::int AS ride_day_number,
        EXTRACT(HOUR FROM c.started_at)::int AS ride_hour,

        CASE
            WHEN EXTRACT(ISODOW FROM c.started_at) IN (6, 7)
                THEN 'Weekend'
            ELSE 'Weekday'
        END AS weekday_type,

        EXTRACT(EPOCH FROM (c.ended_at - c.started_at)) / 60.0 AS ride_duration_minutes,

        c.start_station_id,
        c.start_station_name,
        c.end_station_id,
        c.end_station_name,

        c.start_lat,
        c.start_lng,
        c.end_lat,
        c.end_lng,

        ST_SetSRID(
            ST_MakePoint(c.start_lng, c.start_lat),
            4326
        ) AS start_geom,

        ST_SetSRID(
            ST_MakePoint(c.end_lng, c.end_lat),
            4326
        ) AS end_geom

    FROM jersey_city AS c
    WHERE
        c.ride_id IS NOT NULL
        AND c.started_at IS NOT NULL
        AND c.ended_at IS NOT NULL
        AND c.ended_at > c.started_at
        AND c.start_lat IS NOT NULL
        AND c.start_lng IS NOT NULL
        AND c.end_lat IS NOT NULL
        AND c.end_lng IS NOT NULL
)

SELECT
    r.ride_id,
    r.rideable_type,
    r.member_casual,

    r.started_at,
    r.ended_at,
    r.ride_date,
    r.ride_year,
    r.ride_quarter,
    r.ride_month,
    TRIM(r.ride_month_name) AS ride_month_name,
    TRIM(r.ride_day_of_week) AS ride_day_of_week,
    r.ride_day_number,
    r.ride_hour,
    r.weekday_type,

    r.ride_duration_minutes,

    r.start_station_id,
    r.start_station_name,
    r.end_station_id,
    r.end_station_name,

    r.start_lat,
    r.start_lng,
    r.end_lat,
    r.end_lng,

    start_n.neighborhood AS start_neighborhood,
    end_n.neighborhood AS end_neighborhood,

    ST_Distance(
        r.start_geom::geography,
        r.end_geom::geography
    ) / 1000.0 AS distance_km,

    CASE
        WHEN ST_Distance(r.start_geom::geography, r.end_geom::geography) / 1000.0 < 1
            THEN 'Short'
        WHEN ST_Distance(r.start_geom::geography, r.end_geom::geography) / 1000.0 < 3
            THEN 'Medium'
        ELSE 'Long'
    END AS distance_group,

    CASE
        WHEN r.ride_duration_minutes < 10
            THEN 'Short'
        WHEN r.ride_duration_minutes < 30
            THEN 'Medium'
        ELSE 'Long'
    END AS duration_group,

    w.temperature_2m_max,
    w.temperature_2m_min,
    w.temperature_2m_mean,
    w.precipitation_sum,
    w.rain_sum,
    w.snowfall_sum,
    w.wind_speed_10m_max,

    CASE
        WHEN w.precipitation_sum > 0
            THEN 'Precipitation'
        ELSE 'No Precipitation'
    END AS precipitation_flag,

    CASE
        WHEN w.temperature_2m_mean < 0
            THEN 'Freezing'
        WHEN w.temperature_2m_mean < 10
            THEN 'Cold'
        WHEN w.temperature_2m_mean < 20
            THEN 'Mild'
        ELSE 'Warm'
    END AS temperature_group

FROM ride_base AS r

LEFT JOIN jersey_weather AS w
    ON r.ride_date = w.date::date

LEFT JOIN jersey_city_neighborhoods AS start_n
    ON ST_Within(r.start_geom, start_n.geometry)

LEFT JOIN jersey_city_neighborhoods AS end_n
    ON ST_Within(r.end_geom, end_n.geometry);
"""

In [64]:
with engine.begin() as connection:
    connection.execute(text(create_tableau_materialized_view_sql))

### Check the Materialized View

In [65]:
query = """
SELECT *
FROM mv_tableau_citibike_dashboard
LIMIT 10;
"""

pd.read_sql(
    query,
    con=engine
)

,ride_id,rideable_type,member_casual,started_at,ended_at,ride_date,ride_year,ride_quarter,ride_month,ride_month_name,...,duration_group,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,precipitation_flag,temperature_group
0,ED1D5B83CBD6D447,classic_bike,casual,2025-11-05 16:22:21.024,2025-11-05 16:49:39.454,2025-11-05,2025,4,11,November,...,Medium,18.3,4.0,11.1,0.0,0.0,0.00,20.6,No Precipitation,Mild
1,001BC742E8788155,electric_bike,member,2025-11-11 13:41:51.107,2025-11-11 13:44:44.259,2025-11-11,2025,4,11,November,...,Short,4.4,0.8,2.4,0.5,0.0,0.35,28.2,Precipitation,Cold
2,C2CDBFD218B9E53E,electric_bike,casual,2025-11-24 17:35:01.611,2025-11-24 18:06:00.299,2025-11-24,2025,4,11,November,...,Long,11.4,4.2,6.8,0.0,0.0,0.00,13.5,No Precipitation,Cold
3,18BA053E3F277E7D,electric_bike,casual,2025-11-17 20:22:45.875,2025-11-17 20:31:31.194,2025-11-17,2025,4,11,November,...,Short,6.2,1.4,4.0,0.0,0.0,0.00,25.5,No Precipitation,Cold
4,34A230BB1B0F730C,electric_bike,casual,2025-11-11 09:36:55.918,2025-11-11 09:49:15.882,2025-11-11,2025,4,11,November,...,Medium,4.4,0.8,2.4,0.5,0.0,0.35,28.2,Precipitation,Cold
5,1384D7162C17111C,electric_bike,member,2025-11-05 17:55:51.190,2025-11-05 18:04:22.612,2025-11-05,2025,4,11,November,...,Short,18.3,4.0,11.1,0.0,0.0,0.00,20.6,No Precipitation,Mild
6,EFB2B66657D8BCCF,electric_bike,member,2025-11-12 18:18:50.876,2025-11-12 18:27:11.709,2025-11-12,2025,4,11,November,...,Short,9.3,2.2,5.5,0.0,0.0,0.00,15.6,No Precipitation,Cold
7,33FA159867A9F24B,electric_bike,member,2025-11-24 17:14:15.804,2025-11-24 17:23:21.248,2025-11-24,2025,4,11,November,...,Short,11.4,4.2,6.8,0.0,0.0,0.00,13.5,No Precipitation,Cold
8,35243E1432B2248A,electric_bike,member,2025-11-03 09:44:21.181,2025-11-03 09:53:25.371,2025-11-03,2025,4,11,November,...,Short,14.0,6.3,10.1,0.1,0.1,0.00,16.3,Precipitation,Mild
9,479703005BCC052E,electric_bike,casual,2025-11-19 21:26:21.663,2025-11-19 21:33:46.073,2025-11-19,2025,4,11,November,...,Short,8.3,2.1,4.8,4.6,3.8,0.56,8.7,Precipitation,Cold

### Check Number of Rows

In [66]:
query = """
SELECT
    COUNT(*) AS number_of_rows
FROM mv_tableau_citibike_dashboard;
"""

pd.read_sql(
    query,
    con=engine
)

   number_of_rows
0          999251

### Check Data Quality

In [67]:
query = """
SELECT
    COUNT(*) AS total_rides,

    COUNT(temperature_2m_mean) AS rides_with_weather,
    COUNT(*) - COUNT(temperature_2m_mean) AS rides_missing_weather,

    COUNT(start_neighborhood) AS rides_with_start_neighborhood,
    COUNT(*) - COUNT(start_neighborhood) AS rides_missing_start_neighborhood,

    COUNT(end_neighborhood) AS rides_with_end_neighborhood,
    COUNT(*) - COUNT(end_neighborhood) AS rides_missing_end_neighborhood,

    COUNT(distance_km) AS rides_with_distance,
    COUNT(*) - COUNT(distance_km) AS rides_missing_distance
FROM mv_tableau_citibike_dashboard;
"""

pd.read_sql(
    query,
    con=engine
)

,total_rides,rides_with_weather,rides_missing_weather,rides_with_start_neighborhood,rides_missing_start_neighborhood,rides_with_end_neighborhood,rides_missing_end_neighborhood,rides_with_distance,rides_missing_distance
0,999251,999249,2,547065,452186,542737,456514,999251,0

### Create Indexes on the Materialized View

In [68]:

with engine.begin() as connection:
    connection.execute(text("""
        CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_tableau_ride_id
        ON mv_tableau_citibike_dashboard (ride_id);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_ride_date
        ON mv_tableau_citibike_dashboard (ride_date);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_ride_month
        ON mv_tableau_citibike_dashboard (ride_year, ride_month);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_ride_hour
        ON mv_tableau_citibike_dashboard (ride_hour);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_member_casual
        ON mv_tableau_citibike_dashboard (member_casual);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_rideable_type
        ON mv_tableau_citibike_dashboard (rideable_type);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_start_station
        ON mv_tableau_citibike_dashboard (start_station_name);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_end_station
        ON mv_tableau_citibike_dashboard (end_station_name);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_start_neighborhood
        ON mv_tableau_citibike_dashboard (start_neighborhood);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_end_neighborhood
        ON mv_tableau_citibike_dashboard (end_neighborhood);
    """))

### Refresh Materialized View

In [70]:


with engine.begin() as connection:
    connection.execute(
        text("REFRESH MATERIALIZED VIEW mv_tableau_citibike_dashboard;")
    )

### Concurrent Refresh

In [71]:
with engine.begin() as connection:
    connection.execute(
        text("REFRESH MATERIALIZED VIEW CONCURRENTLY mv_tableau_citibike_dashboard;")
    )

### Create Helper Function to Refresh the Dashboard View

In [72]:

def refresh_tableau_dashboard_view(engine, concurrently=False):
    if concurrently:
        refresh_sql = """
        REFRESH MATERIALIZED VIEW CONCURRENTLY mv_tableau_citibike_dashboard;
        """
    else:
        refresh_sql = """
        REFRESH MATERIALIZED VIEW mv_tableau_citibike_dashboard;
        """

    with engine.begin() as connection:
        connection.execute(text(refresh_sql))

In [73]:

refresh_tableau_dashboard_view(
    engine=engine,
    concurrently=True
)

### Preview Fields for Tableau

In [74]:
query = """
SELECT
    ride_id,
    ride_date,
    ride_month_name,
    ride_day_of_week,
    weekday_type,
    ride_hour,
    rideable_type,
    member_casual,
    start_station_name,
    end_station_name,
    start_neighborhood,
    end_neighborhood,
    ride_duration_minutes,
    duration_group,
    distance_km,
    distance_group,
    temperature_2m_mean,
    temperature_group,
    precipitation_sum,
    precipitation_flag,
    rain_sum,
    snowfall_sum,
    wind_speed_10m_max
FROM mv_tableau_citibike_dashboard
LIMIT 10;
"""

pd.read_sql(
    query,
    con=engine
)

,ride_id,ride_date,ride_month_name,ride_day_of_week,weekday_type,ride_hour,rideable_type,member_casual,start_station_name,end_station_name,...,duration_group,distance_km,distance_group,temperature_2m_mean,temperature_group,precipitation_sum,precipitation_flag,rain_sum,snowfall_sum,wind_speed_10m_max
0,D511D145236ED1F0,2025-10-04,October,Saturday,Weekend,13,electric_bike,member,Exchange Pl,Grand St,...,Short,0.311492,Short,19.5,Mild,0.0,No Precipitation,0.0,0.0,9.4
1,F738E3EA9E5723F2,2025-10-24,October,Friday,Weekday,7,classic_bike,member,Exchange Pl,Montgomery St,...,Medium,1.446784,Medium,10.2,Mild,0.0,No Precipitation,0.0,0.0,11.9
2,324172EC0806C835,2025-10-01,October,Wednesday,Weekday,5,classic_bike,member,Stevens - River Ter & 6 St,Montgomery St,...,Medium,3.323411,Long,16.3,Mild,0.0,No Precipitation,0.0,0.0,14.4
3,483FB22AD2A6D2B3,2025-10-03,October,Friday,Weekday,7,electric_bike,casual,11 St & Washington St,Montgomery St,...,Medium,3.946629,Long,15.5,Mild,0.0,No Precipitation,0.0,0.0,8.9
4,85E1B79984AF428A,2025-10-21,October,Tuesday,Weekday,22,electric_bike,casual,4 St & River St,Montgomery St,...,Medium,3.100566,Long,13.5,Mild,0.1,Precipitation,0.1,0.0,12.7
5,649BDD434701CCC2,2025-10-10,October,Friday,Weekday,19,electric_bike,casual,4 St & River St,Montgomery St,...,Medium,3.100566,Long,10.9,Mild,0.0,No Precipitation,0.0,0.0,11.4
6,95BA7DCA5AC1EE16,2025-10-14,October,Tuesday,Weekday,22,electric_bike,casual,4 St & River St,Montgomery St,...,Medium,3.100566,Long,13.9,Mild,0.1,Precipitation,0.1,0.0,19.0
7,E37460CAA5DAE232,2025-10-30,October,Thursday,Weekday,19,classic_bike,casual,4 St & River St,Montgomery St,...,Medium,3.100566,Long,13.8,Mild,44.4,Precipitation,44.4,0.0,26.5
8,8C01FBC64EB9968A,2025-10-20,October,Monday,Weekday,7,electric_bike,member,4 St & River St,Grand St,...,Medium,2.976315,Medium,15.8,Mild,10.2,Precipitation,10.2,0.0,23.9
9,3078D74085DE3BC6,2025-10-24,October,Friday,Weekday,21,electric_bike,member,Washington St,Grand St,...,Short,1.029299,Medium,10.2,Mild,0.0,No Precipitation,0.0,0.0,11.9